# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true


# Setup
title:            Masoud Abdi
tagline:          'Personal Website'
description:      'Entrepreneur ğŸ™â€â™‚ï¸ | Multi-cloud Unicorn ğŸ¦„ | Data Scientist (PhD) ğŸ‘¨â€ğŸ’» | AI Engineer ğŸ§‘â€ğŸ”§ | Consultant @ Servian ğŸ§‘â€ğŸ’¼ | GovHack Victoria ğŸ¢ '
url:              https://www.masabdi.com
baseurl:          '/'

author:
  name:           'Masoud Abdi'
  url:            https://www.masabdi.com


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


linkedin:
  repo:           https://www.linkedin.com/in/masabdi/
email:
  gmail:          itsmasabdi@gmail.com
                  